use std::collections::HashSet;
use std::sync::Mutex;
use std::sync::atomic::AtomicUsize;
use lazy_static::lazy_static;
use rand::Rng;
use rusqlite::{params, Connection};

pub type PortId = usize;

lazy_static! {
    static ref NEXT_PORT_ID: AtomicUsize = AtomicUsize::new(1);
}

lazy_static!{
    static ref PORT_NAME_REGISTRY: Mutex<HashSet<String>> = Mutex::new(HashSet::new());
}

pub struct Port {
    pub port_id: PortId,
    port_name: String, // derived from port_name_index
    //TODO resource info... generation/usage per cycle, current cost/price
}

impl Port {
    pub fn new() -> Port {
        let port_id = NEXT_PORT_ID.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
        let mut port_name = format!("Port {}", port_id);

        let mut try_counter = 20;
        while try_counter > 0 {
            try_counter -= 1;
            let index = rand::rng().random_range(0..Self::PORT_NAMES.len());
            let proposed_name = Self::PORT_NAMES[index];
            if !PORT_NAME_REGISTRY.lock().unwrap().contains(proposed_name) {
                port_name = proposed_name.to_owned();
                PORT_NAME_REGISTRY.lock().unwrap().insert(proposed_name.to_owned());
                break;
            }
        }

        Port{port_id, port_name}
    }

    pub fn get_port_id(&self) -> PortId {
        self.port_id
    }

    pub fn get_port_name(&self) -> &String {
        &self.port_name
    }

    /// Writes information about this port to the database.
    /// To be used when the port is first created.
    pub fn persist(&self, database: &Connection) {
        let (statement, result) = {
            // TODO resource columns
            let statement = "INSERT INTO ports (portId, portName) VALUES (?1, ?2);";
            let params = params![self.port_id, self.port_name];
            (statement, database.execute(statement, params))
        };

        match result {
            Ok(_) => (),
            Err(err) => {
                println!("Database error: {}", err);
                println!("{}", statement);
                panic!("Shutting down");
            }
        }
    }

    // List of pre-built port names - corresponds to the port_name_index value.
    // You can add names to this list without reinitializing your game, but this will cause
    // all of your port names to change beyond the point at which you first added a name.
    // It is strongly recommended that you not remove names from this list without reinitialization.
    const PORT_NAMES: &'static [&'static str] = &[
        "A-A-Ron",
        "Abercrombie",
        "Acupunk",
        "Ada",
        "Addendum",
        "Aesculus",
        "After-party",
        "Agamemnon",
        "Ah So",
        "Aighhhh",
        "Aja",
        "Akronim",
        "Alabama",
        "Alexander",
        "Alexandria",
        "Alpha",
        "Alphonse",
        "Alyssia",
        "Ambergris",
        "Andromeda",
        "Anonymous",
        "Apoplexy",
        "Apportionment",
        "Appolonia",
        "Aquatic Bird",
        "Arggghhh",
        "Arizona",
        "Aroustabout",
        "Arrietty",
        "Arya's Dagger",
        "Ash hole",
        "Atomic Mud",
        "Atomizer",
        "Attila",
        "Aunt Gertrude",
        "Aurolophy",
        "Avuncular",
        "Awash In Grateness",
        "awk",
        "Axlotl",
        "Ayana",
        "BachHead",
        "Banana Peel",
        "Bandana Fiend",
        "BandMaid",
        "Beethoven",
        "Belinda",
        "Belly Dancer",
        "Bent Guppy",
        "Beta",
        "Bird in a Bush",
        "Bishop's Bet",
        "Black Company",
        "Blue Orajel",
        "Brazilian",
        "Bre'r Rabbi",
        "Bún Bò Huế",
        "Burunda",
        "Calliope",
        "Cambridge",
        "Camelot",
        "Cañon City",
        "Canebrake",
        "Cassandra",
        "Cassiopeia",
        "Catspaw",
        "Cecily",
        "Chameleon",
        "Chet's Dream",
        "China Beach",
        "Chinos",
        "Chloe",
        "Chop Stick",
        "Chopin",
        "Church Ranch",
        "Cicada",
        "Clarisse",
        "Clementine",
        "Clever Girl",
        "Clutz",
        "Coop Mart",
        "Countdown",
        "Damascus",
        "Đàn tranh",
        "Deaf Leperd",
        "Debris Field",
        "December",
        "Dedisse",
        "Defender",
        "Degraded Disk",
        "Dei Agnus",
        "Delicious Dorcus",
        "Demented Dog",
        "Dementor House",
        "Denali",
        "Denatured Algol",
        "Denethor",
        "Desert Watch",
        "Dirty Pair",
        "Dispassionate Donkey",
        "Dogpatch",
        "Doktari",
        "Don Quixote",
        "Doofus Department",
        "Dotsero",
        "Dream Theatrix",
        "Dubstep",
        "Earworm",
        "EbbAndFlow",
        "Eccentricity",
        "Ed",
        "Eddy's Time Current",
        "Edelweiss",
        "Effigy",
        "Effluent",
        "Egg Sauce",
        "Ein Zwei",
        "Elaine's Lane",
        "Electric Eel",
        "Elegant",
        "Elegy",
        "Embryonic Egg",
        "Emma Tu",
        "Emmaeus",
        "Engenio",
        "Ero-naughty-gal",
        "Eros",
        "Escroger",
        "Fabrique",
        "Facile",
        "Faded Pooch",
        "Fae Filly",
        "Failure Mode",
        "Fall Mouth",
        "Fatal Stop",
        "Fathead",
        "Feeding Trough",
        "Felony",
        "Femme Fatale",
        "Fender Bender",
        "Figgy Pudding",
        "Filossafur",
        "Financial Ruin",
        "Fire in your hole",
        "Flatiron",
        "Flossful",
        "Flounder",
        "Foggy Bottom",
        "Foghorn",
        "Ford Prefect",
        "Fortunate Sun",
        "Fudge Vanilla",
        "Fun Gully",
        "Fun Times",
        "Funny Business",
        "Futile",
        "Fuzzy Logic",
        "Galipoli",
        "Galloping Gourmet",
        "Gamma",
        "Gandolf",
        "Garfield",
        "Gaslight",
        "Gastronomic Disaster",
        "Gato Loco",
        "Gattling Gunn",
        "Gazpacho",
        "Gemma",
        "Gertie's Place",
        "Gimme Chocolate",
        "Godot",
        "Gourd Hole",
        "GPGPU",
        "GrabBag",
        "Graditum Ferociter",
        "Grandma's House",
        "Greenhouse",
        "Grinch",
        "Grizelda",
        "Guardrail",
        "Habitat",
        "Had Enough",
        "Ham Sandwich",
        "Hammer Thyme",
        "Hamster Road",
        "Handout",
        "Handsome Stranger",
        "Haul-Donkey",
        "Hazmat",
        "HeadCase",
        "HeadStone",
        "Hedon",
        "HeelToToe",
        "Hefty Fine",
        "Hegemon",
        "Helfyre",
        "Hemp",
        "Henna",
        "Hephastus",
        "Her Bedroom",
        "Hiccup",
        "Hidden Leisure",
        "Hideaway",
        "Highline Canal",
        "Highrise",
        "Hilarity",
        "Him Go Here",
        "Hindenberg",
        "Hipster",
        "Hiromi",
        "Historical Hyena",
        "Hit Man",
        "Hive Mynd",
        "HobNob",
        "Hoch",
        "Hoedown",
        "Hoggery",
        "Hogwash",
        "Hoi Polloi",
        "Hollerith",
        "Hollyhock",
        "Holy Roly Poly",
        "Hombre House",
        "Honor Lightman",
        "Hooman Kloset",
        "Hopalong",
        "Horrors Galore",
        "Hose Meister",
        "Hostage Hotel",
        "Hostel",
        "Hot Girl",
        "Hot L Baltimore",
        "Hotcake Corner",
        "Hotpot",
        "House of Pancake",
        "Hovercraft",
        "Howitzer Palace",
        "Hozzy Hozbourne",
        "Huế",
        "Huge Ackman",
        "Hugh Janus",
        "Humbucker",
        "Hun the Attila",
        "Hung High",
        "Ibrahim",
        "Ibiza",
        "Icarus",
        "Ice Palace",
        "Id",
        "Ida Know",
        "Ide Suv March",
        "Idolwilde",
        "Idyllica",
        "Iggy's Pop",
        "Ikky Poo Wah",
        "I'll be back",
        "Illogic Gate",
        "Illuminati",
        "Illusion Of Hope",
        "Illustra",
        "Imbecile",
        "Imugi",
        "Inbreathiation",
        "Indictment",
        "Indigo",
        "Ingress",
        "Initial Dot",
        "Internet 404",
        "Io",
        "Ip Man",
        "Ipswitch",
        "Irrational Rat",
        "Istanbull",
        "Itchy Finger",
        "It's not yours",
        "IU",
        "Ix",
        "JackBeNimble",
        "Jaded Strumpet",
        "Jam",
        "Janice Jump",
        "Jefferson",
        "Jellyroll",
        "Jilted Bride",
        "Jimmy's Cracked Corn",
        "Jirisan",
        "Jitter",
        "Joffrey's Bow",
        "Jumpstart",
        "Kiki's Delivery Service",
        "Kirika",
        "Kim Chi Palace",
        "Khrysxander",
        "Land Rooster",
        "Larry Larva",
        "Leaf on the Wind",
        "LeeLee",
        "Leon",
        "Lewellen's Landing",
        "Lianna",
        "Lilian",
        "Liqid Lunch",
        "Liquid Burrito",
        "Lisandra",
        "Lizzy's Fat",
        "Logical Shift Left",
        "Logical Shift Right",
        "Lonely Lyrica",
        "Lost Sock",
        "Low Taper Fade",
        "Lucy21",
        "Macedonia",
        "Mad at the World",
        "Made In Japan",
        "Madlax",
        "Mafia Mart",
        "Magic Mushroom",
        "Ma-gun",
        "Mahler",
        "Maker",
        "Malletface",
        "Mammary Gland",
        "Man o' War",
        "Manipulous",
        "Manticore",
        "Mary Jane",
        "Marvin",
        "Mass Hallucination",
        "Masterpiece",
        "Matilda",
        "Matterhorn",
        "Maverick",
        "Maybe Knot",
        "Mayhem",
        "Mellow Tonin",
        "Memory Loss",
        "Mental Flog",
        "Mephisto",
        "Mob Rule",
        "Mock Turtle",
        "Mod Skwad",
        "Model Train",
        "Moffat Jungle",
        "Molar Extraction",
        "Money Pit",
        "Mongo",
        "Monkey in the Bush",
        "Mononoke",
        "Moriarty",
        "Mot Hai Ba",
        "Motel California",
        "Mothball",
        "Mousetrap",
        "Move Over",
        "Mozart",
        "Mozzle Tov",
        "Nachine",
        "Nada Problem",
        "Nadz",
        "Nagging Headache",
        "Namaste",
        "NanoByte",
        "Napoleon Blownapart",
        "Nap Time",
        "Naruto's Restaurant",
        "Nasty Femme",
        "Natalie",
        "Nature's End",
        "Nausicaä",
        "Navigational Hazard",
        "Neck Pain",
        "Ned's Place",
        "Needs Work",
        "Nerd Base",
        "Nest of Snakes",
        "Net of Fish",
        "Nevada",
        "New Port",
        "Newt's Demise",
        "Nexus",
        "Nha Trang",
        "Nickel-less Cage",
        "No Name",
        "Nog",
        "Not Here",
        "Notty Pine",
        "No Tan Lines",
        "No Way Jose",
        "No Way Around",
        "No Way In",
        "No Way Out",
        "No Way Over",
        "No Way Under",
        "NonBinary",
        "Nozzle",
        "Nude Beach",
        "Numbnutz",
        "Nutcase",
        "Obstructed",
        "Obtuse",
        "Ocelot Lot",
        "Octagon",
        "October",
        "Octopussy",
        "Oddball",
        "Oedipus Tex",
        "Often Imitated",
        "Oh My Ghostess",
        "Oi!",
        "Olga's Loogy",
        "Oligarchy",
        "Oliphaunt Cage",
        "Omnippa Tent",
        "On Time",
        "Onnatop",
        "Opera-tic",
        "Optional Truce",
        "Over There",
        "Overload",
        "Oy!",
        "Oz",
        "Pablo Esco's Bar",
        "Pac Man",
        "Pacemaker",
        "Packrat",
        "Pad Thai",
        "Paid Off",
        "Pair of Pants",
        "Paladin",
        "Palm Oil",
        "Pam Hollister",
        "Pamela Sue-Ann Derson",
        "Pandemonium",
        "Panky Hanky",
        "Parenthetical",
        "Park Place",
        "Parker",
        "Pentagon",
        "Penthouse",
        "Perquisite",
        "Petting Zoo",
        "Petunia",
        "Pfoo",
        "Phantastic",
        "Philistine",
        "Phlap Jack",
        "Phở Queue",
        "Phoenix",
        "Philosopher",
        "Phlorescent",
        "Phosphorous",
        "Phú Quốc",
        "Pickup",
        "Pie Hole",
        "Pigpen",
        "Plugh",
        "Ponyo",
        "Porco Rosso",
        "Primo",
        "Ptarmigan",
        "Qanat",
        "Quay Lewd",
        "Qubic",
        "Quark",
        "QuestFerFire",
        "Rabbi Mole",
        "Rabbit Hole",
        "Rabid Germ",
        "Racetrack",
        "Rachel's Room",
        "Racine",
        "Radical Red",
        "Radioactive",
        "Rafter",
        "Raging Dork",
        "Ragweed",
        "Rainman",
        "Rajah",
        "Rake",
        "Rambo",
        "Rambunctious",
        "Random Death",
        "Raptor Nest",
        "Raquel",
        "Ranch-in-a-box",
        "Ransom",
        "Rare Earth",
        "Raspberry Patch",
        "Rasta-furry",
        "Rat Burger",
        "Rat Hole",
        "Ratatata-tata",
        "Rave",
        "Raw Wound",
        "Rebel",
        "Reckless",
        "RedBeard",
        "Redneck",
        "Red Robe",
        "Reeeee",
        "Referee",
        "Registered Ghoul",
        "Render Fiend",
        "Renee",
        "Renovated",
        "Rent Free",
        "RibEye",
        "Rice Field",
        "Ride Fast",
        "Rift In Time",
        "Rigged Election",
        "Right Away",
        "Rim of the World",
        "Rinko",
        "Rio Grande",
        "Ripley's Perch",
        "Ripoff",
        "Rise",
        "Rising Sun",
        "Ritch",
        "Rival Watch",
        "Robber Baron",
        "Rocinate",
        "Roddy McDowel",
        "Roger Rabbit",
        "Rolling Thunder",
        "Rome In A Day",
        "Rondo",
        "Rope Tied",
        "Roswell",
        "Rotting Hood",
        "Roving Horde",
        "RowYerBoat",
        "Roy",
        "Rusty Pelican",
        "Rusty Rench",
        "Sabbath",
        "Sacagawea",
        "Sack in the Box",
        "Sack o' Suds",
        "Sad Place",
        "Safe Place",
        "Saggy Butt",
        "Salon Pass",
        "Samwidge",
        "Sanitary Napikin",
        "Sao Paulo",
        "Sappy Time",
        "Sarte",
        "Sarcophagus",
        "Sassy Missy",
        "Satrap",
        "Satriani",
        "Saving Time",
        "Sawbones",
        "Saxophone",
        "Say Nothing",
        "Sea of Silence",
        "Secret Pork",
        "sed",
        "Sedentary",
        "See Nothing",
        "Segue",
        "Segundo",
        "Sellout",
        "Semaphore",
        "Senile",
        "Sent Away",
        "Separated Disk",
        "September",
        "Sequestered",
        "Serpent's Store",
        "Serrated",
        "Settler's Rest",
        "Settle Down Beavis",
        "Severed Artery",
        "Sew Hot",
        "Seychelle",
        "Sez You",
        "Shallot",
        "Shepherd Pie",
        "Sherlock",
        "She Said",
        "SheBoyGun",
        "Shipwreck",
        "Shiv",
        "Shoe Chee",
        "Shoe Horn",
        "Shogun",
        "Shopping Suzy",
        "Shut Up",
        "Sibling Rivalry",
        "Sick Bucket",
        "Sideways",
        "Sifted Flour",
        "Sigh",
        "Sigh Gone",
        "Sightless",
        "Silly Fun",
        "Simple Port",
        "Singles Only",
        "Sip of Soup",
        "Sir Hiss",
        "Sister Shoe",
        "Sit Down",
        "Six Pence",
        "Sizemore",
        "So Close",
        "S.O.B.",
        "Sob Story",
        "Socrates",
        "Sod Off",
        "Softer Pillow",
        "Soggy Pants",
        "Soho",
        "Sole Survivor",
        "Something Else",
        "Sonny and Chair",
        "Sopwith Camel",
        "Sorry 'Bout That",
        "Soup Bowl",
        "South Chutes",
        "Sowth of the Boarder",
        "Spaced Ex",
        "Squid",
        "Squirm",
        "Squish",
        "Step Up",
        "Stool Pigeon",
        "Stupid Thing",
        "Sugar Lips",
        "Sweaty Pitz",
        "Swiss Cheese",
        "Sybil",
        "Synesthesia",
        "Taboo",
        "TackleBox",
        "Taco Bull",
        "Tad Less",
        "Taffy Maker",
        "Tagline",
        "Tai Chi",
        "Taj Mahal",
        "Take-out",
        "Tally-Ho",
        "Tame Tiger",
        "Tank",
        "Tao",
        "Tap Dance",
        "Tar Pit",
        "Tasmania",
        "Tats",
        "Taxes R Theft",
        "Taylor Whiffed",
        "Technical Debt",
        "Teddy's Tavern",
        "Tee Off",
        "Teflon",
        "Tek War",
        "Telecaster",
        "Telefoam",
        "Temerity",
        "Tenacious",
        "Tequila Moonrise",
        "Tercero",
        "Terminated",
        "Testing 1, 2, 3",
        "Third Martini",
        "Thirteenth Step",
        "Threadbare",
        "Three Somethings",
        "Thor's Hummer",
        "Tic Tac Toe",
        "Tickle Me",
        "Tied Up",
        "Tighter Pleese",
        "Tiller",
        "Tim bucked two",
        "Tin Horn",
        "Tip of the Iceberg",
        "Toggle",
        "Token Dude",
        "Toll Road",
        "Tomorrow",
        "Tone Deaf",
        "Too Tired",
        "Top Gear",
        "Top Hat",
        "Topless Tina's Tent",
        "Torrent",
        "Tostesterone",
        "Trader Cho",
        "Trans Sister",
        "Transylvania",
        "Treadstone",
        "Trellis",
        "Trouble",
        "Tsunami",
        "Turtle Creek",
        "Turtle Eater",
        "Udder Failure",
        "Ugh",
        "Ukelele",
        "Ultimate Nothing",
        "Underwear",
        "Vanna Wyte",
        "Vending Machine",
        "Verve",
        "Vibraphone",
        "Vicky's Chow",
        "Villain",
        "vim",
        "Vanadium",
        "Welease Wodewick",
        "Wobbly Gun",
        "Xyzzy",
        "XL Academy",
        "Yag Laser",
        "Yard Store",
        "Yazoo City",
        "Yellow Bus Marine",
        "Yippee Kai Yay",
        "Yo Adrian",
        "Your mom is a port",
        "Zeus",
        "Zipline",
        "Zoom",
        "Zorro",
        "Zuplicate",
        "김밥",
        "天安门广场",
        "十面埋伏",
    ];
}
