use std::sync::Mutex;
use crate::sector::SectorId;

pub type PortId = u32;

static NEXT_PORT_ID: Mutex<PortId> = Mutex::new(1);

pub struct Port {
    pub port_id: PortId,
    port_name_index: Option<usize>,
    pub sector_id: SectorId,
    //TODO resource info... generation/usage per cycle, current cost/price
}

impl Port {
    // TODO need a create_from_database which updates NEXT_PORT_ID appropriately

    pub fn new(port_name_index: usize, sector_id: SectorId) -> Port {
        let mut pni : Option<usize> = None;
        if port_name_index < PORT_NAMES.len() {
            pni = Some(port_name_index);
        }

        let mut next_id = NEXT_PORT_ID.lock().unwrap();
        let port_id = *next_id;
        *next_id += 1;
        Port{port_id, port_name_index: pni, sector_id: sector_id}
    }

    pub fn get_port_name(&self) -> String {
        if self.port_name_index.is_some() {
            String::from(PORT_NAMES[*(self.port_name_index.as_ref().unwrap())])
        } else {
            format!("Port {}", self.port_id)
        }
    }
}

// You can add names to this list without reinitializing your game, but this will cause
// all of your port names to change beyond the point at which you first added a name.
// It is strongly recommended that you not remove names from this list without reinitialization.
pub const PORT_NAMES: &'static [&'static str] = &[
    "A-A-Ron",
    "Abercrombie",
    "Acupunk",
    "Ada",
    "Addendum",
    "Aesculus",
    "After-party",
    "Agamemnon",
    "Ah So",
    "Aighhhh",
    "Aja",
    "Akronim",
    "Alabama",
    "Alexander",
    "Alexandria",
    "Alpha",
    "Alphonse",
    "Alyssia",
    "Ambergris",
    "Andromeda",
    "Anonymous",
    "Apoplexy",
    "Apportionment",
    "Appolonia",
    "Aquatic Bird",
    "Arggghhh",
    "Arizona",
    "Aroustabout",
    "Arrietty",
    "Arya's Dagger",
    "Ash hole",
    "Atomic Mud",
    "Atomizer",
    "Attila",
    "Aunt Gertrude",
    "Aurolophy",
    "Avuncular",
    "Awash In Grateness",
    "awk",
    "Axlotl",
    "Ayana",
    "BachHead",
    "Banana Peel",
    "Bandana Fiend",
    "BandMaid",
    "Beethoven",
    "Belinda",
    "Belly Dancer",
    "Bent Guppy",
    "Beta",
    "Bird in a Bush",
    "Bishop's Bet",
    "Black Company",
    "Brazilian",
    "Bre'r Rabbi",
    "Bún Bò Huế",
    "Burunda",
    "Calliope",
    "Cambridge",
    "Camelot",
    "Cañon City",
    "Canebrake",
    "Cassandra",
    "Cassiopeia",
    "Catspaw",
    "Cecily",
    "Chameleon",
    "Chet's Dream",
    "China Beach",
    "Chinos",
    "Chloe",
    "Chop Stick",
    "Chopin",
    "Church Ranch",
    "Cicada",
    "Clarisse",
    "Clementine",
    "Clever Girl",
    "Clutz",
    "Coop Mart",
    "Countdown",
    "Damascus",
    "Đàn tranh",
    "Deaf Leperd",
    "Debris Field",
    "December",
    "Dedisse",
    "Defender",
    "Degraded Disk",
    "Dei Agnus",
    "Delicious Dorcus",
    "Demented Dog",
    "Dementor House",
    "Denali",
    "Denatured Algol",
    "Denethor",
    "Desert Watch",
    "Dirty Pair",
    "Dispassionate Donkey",
    "Dogpatch",
    "Doktari",
    "Don Quixote",
    "Doofus Department",
    "Dotsero",
    "Dream Theatrix",
    "Dubstep",
    "Earworm",
    "EbbAndFlow",
    "Eccentricity",
    "Ed",
    "Eddy's Time Current",
    "Edelweiss",
    "Effigy",
    "Effluent",
    "Egg Sauce",
    "Ein Zwei",
    "Elaine's Lane",
    "Electric Eel",
    "Elegant",
    "Elegy",
    "Embryonic Egg",
    "Emmaeus",
    "Eros",
    "Escroger",
    "Fabrique",
    "Facile",
    "Faded Pooch",
    "Fae Filly",
    "Failure Mode",
    "Fall Mouth",
    "Fatal Stop",
    "Fathead",
    "Feeding Trough",
    "Felony",
    "Femme Fatale",
    "Fender Bender",
    "Figgy Pudding",
    "Filossafur",
    "Financial Ruin",
    "Fire in your hole",
    "Flatiron",
    "Flossful",
    "Flounder",
    "Foggy Bottom",
    "Foghorn",
    "Ford Prefect",
    "Fortunate Sun",
    "Fudge Vanilla",
    "Fun Times",
    "Funny Business",
    "Futile",
    "Fuzzy Logic",
    "Galipoli",
    "Galloping Gourmet",
    "Gamma",
    "Gandolf",
    "Garfield",
    "Gaslight",
    "Gastronomic Disaster",
    "Gattling Gunn",
    "Gazpacho",
    "Gemma",
    "Gertie's Place",
    "Gimme Chocolate",
    "Godot",
    "Gourd Hole",
    "GPGPU",
    "GrabBag",
    "Grandma's House",
    "Greenhouse",
    "Grinch",
    "Grizelda",
    "Guardrail",
    "Habitat",
    "Had Enough",
    "Ham Sandwich",
    "Hammer Thyme",
    "Hamster Road",
    "Handout",
    "Haul-Donkey",
    "Hazmat",
    "HeadCase",
    "HeadStone",
    "Hedon",
    "HeelToToe",
    "Hefty Fine",
    "Hegemon",
    "Helfyre",
    "Hemp",
    "Henna",
    "Hephastus",
    "Her Bedroom",
    "Hiccup",
    "Hidden Leisure",
    "Hideaway",
    "Highline Canal",
    "Highrise",
    "Hilarity",
    "Him Go Here",
    "Hindenberg",
    "Hipster",
    "Hiromi",
    "Historical Hyena",
    "Hit Man",
    "Hive Mynd",
    "HobNob",
    "Hoch",
    "Hoedown",
    "Hoggery",
    "Hogwash",
    "Hoi Polloi",
    "Hollerith",
    "Hollyhock",
    "Holy Roly Poly",
    "Hombre House",
    "Honor Lightman",
    "Hooman Kloset",
    "Hopalong",
    "Horrors Galore",
    "Hose Meister",
    "Hostage Hotel",
    "Hostel",
    "Hot Girl",
    "Hot L Baltimore",
    "Hotcake Corner",
    "Hotpot",
    "House of Pancake",
    "Hovercraft",
    "Howitzer Palace",
    "Hozzy Hozbourne",
    "Huế",
    "Huge Ackman",
    "Hugh Janus",
    "Humbucker",
    "Hun the Attila",
    "Hung High",
    "Ibrahim",
    "Ibiza",
    "Icarus",
    "Ice Palace",
    "Id",
    "Ida Know",
    "Ide Suv March",
    "Idolwilde",
    "Idyllica",
    "Iggy's Pop",
    "Ikky Poo Wah",
    "I'll be back",
    "Illuminati",
    "Illusion Of Hope",
    "Illustra",
    "Imbecile",
    "Imugi",
    "Inbreathiation",
    "Indictment",
    "Indigo",
    "Ingress",
    "Initial Dot",
    "Internet 404",
    "Io",
    "Ip Man",
    "Ipswitch",
    "Irrational Rat",
    "Istanbull",
    "Itchy Finger",
    "It's not yours",
    "IU",
    "Ix",
    "JackBeNimble",
    "Jaded Strumpet",
    "Jam",
    "Janice Jump",
    "Jefferson",
    "Jellyroll",
    "Jilted Bride",
    "Jimmy's Cracked Corn",
    "Jirisan",
    "Jitter",
    "Joffrey's Bow",
    "Jumpstart",
    "Kiki's Delivery Service",
    "Kirika",
    "Kim Chi Palace",
    "Khrysxander",
    "Land Rooster",
    "Larry Larva",
    "Leaf on the Wind",
    "LeeLee",
    "Leon",
    "Lianna",
    "Lilian",
    "Liqid Lunch",
    "Liquid Burrito",
    "Lisandra",
    "Lizzy's Fat",
    "Logical Shift Left",
    "Logical Shift Right",
    "Lonely Lyrica",
    "Lost Sock",
    "Low Taper Fade",
    "Lucy21",
    "Macedonia",
    "Mad at the World",
    "Made In Japan",
    "Madlax",
    "Mafia Mart",
    "Magic Mushroom",
    "Ma-gun",
    "Mahler",
    "Maker",
    "Malletface",
    "Mammary Gland",
    "Man o' War",
    "Manipulous",
    "Manticore",
    "Mary Jane",
    "Marvin",
    "Mass Hallucination",
    "Masterpiece",
    "Matilda",
    "Matterhorn",
    "Maverick",
    "Maybe Knot",
    "Mayhem",
    "Mellow Tonin",
    "Memory Loss",
    "Mental Flog",
    "Mephisto",
    "Mob Rule",
    "Mock Turtle",
    "Mod Skwad",
    "Model Train",
    "Moffat Jungle",
    "Molar Extraction",
    "Money Pit",
    "Mongo",
    "Monkey in the Bush",
    "Mononoke",
    "Moriarty",
    "Mot Hai Ba",
    "Mothball",
    "Mousetrap",
    "Move Over",
    "Mozart",
    "Mozzle Tov",
    "Nachine",
    "Nada Problem",
    "Nadz",
    "Nagging Headache",
    "Namaste",
    "NanoByte",
    "Napoleon Blownapart",
    "Nap Time",
    "Naruto's Restaurant",
    "Nasty Femme",
    "Natalie",
    "Nature's End",
    "Nausicaä",
    "Navigational Hazard",
    "Neck Pain",
    "Ned's Place",
    "Needs Work",
    "Nerd Base",
    "Nest of Snakes",
    "Net of Fish",
    "Nevada",
    "New Port",
    "Newt's Demise",
    "Nexus",
    "Nha Trang",
    "Nickel-less Cage",
    "No Name",
    "Nog",
    "Not Here",
    "Notty Pine",
    "No Way Jose",
    "No Way Around",
    "No Way In",
    "No Way Out",
    "No Way Over",
    "No Way Under",
    "NonBinary",
    "Nozzle",
    "Nude Beach",
    "Numbnutz",
    "Nutcase",
    "Obstructed",
    "Obtuse",
    "Ocelot Lot",
    "Octagon",
    "October",
    "Octopussy",
    "Oddball",
    "Oedipus Tex",
    "Often Imitated",
    "Oh My Ghostess",
    "Oi!",
    "Olga's Loogy",
    "Oligarchy",
    "Oliphaunt Cage",
    "Omnippa Tent",
    "On Time",
    "Onnatop",
    "Opera-tic",
    "Optional Truce",
    "Over There",
    "Overload",
    "Oy!",
    "Oz",
    "Pablo Esco's Bar",
    "Pac Man",
    "Pacemaker",
    "Packrat",
    "Pad Thai",
    "Paid Off",
    "Pair of Pants",
    "Paladin",
    "Palm Oil",
    "Pam Hollister",
    "Pamela Sue-Ann Derson",
    "Pandemonium",
    "Panky Hanky",
    "Parenthetical",
    "Park Place",
    "Parker",
    "Pentagon",
    "Penthouse",
    "Perquisite",
    "Petting Zoo",
    "Petunia",
    "Pfoo",
    "Phantastic",
    "Philistine",
    "Phlap Jack",
    "Phở Queue",
    "Phoenix",
    "Philosopher",
    "Phlorescent",
    "Phosphorous",
    "Phú Quốc",
    "Pickup",
    "Pie Hole",
    "Pigpen",
    "Plugh",
    "Ponyo",
    "Porco Rosso",
    "Primo",
    "Ptarmigan",
    "Qanat",
    "Quay Lewd",
    "Qubic",
    "Quark",
    "QuestFerFire",
    "Rabbi Mole",
    "Rabbit Hole",
    "Rabid Germ",
    "Racetrack",
    "Rachel's Room",
    "Racine",
    "Radical Red",
    "Radioactive",
    "Rafter",
    "Raging Dork",
    "Ragweed",
    "Rainman",
    "Rajah",
    "Rake",
    "Rambo",
    "Rambunctious",
    "Random Death",
    "Raptor Nest",
    "Raquel",
    "Ranch-in-a-box",
    "Ransom",
    "Rare Earth",
    "Raspberry Patch",
    "Rasta-furry",
    "Rat Burger",
    "Rat Hole",
    "Ratatata-tata",
    "Rave",
    "Raw Wound",
    "Rebel",
    "Reckless",
    "RedBeard",
    "Redneck",
    "Red Robe",
    "Reeeee",
    "Referee",
    "Registered Ghoul",
    "Render Fiend",
    "Renee",
    "Renovated",
    "Rent Free",
    "RibEye",
    "Rice Field",
    "Ride Fast",
    "Rift In Time",
    "Rigged Election",
    "Right Away",
    "Rim of the World",
    "Rinko",
    "Rio Grande",
    "Ripley's Perch",
    "Ripoff",
    "Rise",
    "Ritch",
    "Rival Watch",
    "Robber Baron",
    "Rocinate",
    "Roddy McDowel",
    "Roger Rabbit",
    "Rolling Thunder",
    "Rome In A Day",
    "Rondo",
    "Rope Tied",
    "Roswell",
    "Rotting Hood",
    "Roving Horde",
    "RowYerBoat",
    "Roy",
    "Rusty Rench",
    "Sabbath",
    "Sacagawea",
    "Sack in the Box",
    "Sack o' Suds",
    "Sad Place",
    "Safe Place",
    "Saggy Butt",
    "Salon Pass",
    "Samwidge",
    "Sanitary Napikin",
    "Sao Paulo",
    "Sappy Time",
    "Sarte",
    "Sarcophagus",
    "Sassy Missy",
    "Satrap",
    "Satriani",
    "Saving Time",
    "Sawbones",
    "Saxophone",
    "Say Nothing",
    "Sea of Silence",
    "Secret Pork",
    "sed",
    "Sedentary",
    "See Nothing",
    "Segue",
    "Segundo",
    "Sellout",
    "Semaphore",
    "Senile",
    "Sent Away",
    "Separated Disk",
    "September",
    "Sequestered",
    "Serpent's Store",
    "Serrated",
    "Settler's Rest",
    "Settle Down Beavis",
    "Severed Artery",
    "Sew Hot",
    "Seychelle",
    "Sez You",
    "Shallot",
    "Shepherd Pie",
    "Sherlock",
    "She Said",
    "SheBoyGun",
    "Shipwreck",
    "Shiv",
    "Shoe Chee",
    "Shoe Horn",
    "Shogun",
    "Shopping Suzy",
    "Shut Up",
    "Sibling Rivalry",
    "Sick Bucket",
    "Sideways",
    "Sifted Flour",
    "Sigh",
    "Sightless",
    "Silly Fun",
    "Simple Port",
    "Singles Only",
    "Sip of Soup",
    "Sir Hiss",
    "Sister Shoe",
    "Sit Down",
    "Six Pence",
    "Sizemore",
    "So Close",
    "S.O.B.",
    "Sob Story",
    "Socrates",
    "Sod Off",
    "Softer Pillow",
    "Soggy Pants",
    "Soho",
    "Sole Survivor",
    "Something Else",
    "Sonny and Chair",
    "Sopwith Camel",
    "Sorry 'Bout That",
    "Soup Bowl",
    "South Chutes",
    "Sowth of the Boarder",
    "Squid",
    "Squirm",
    "Squish",
    "Step Up",
    "Stool Pigeon",
    "Stupid Thing",
    "Sugar Lips",
    "Sweaty Pitz",
    "Swiss Cheese",
    "Sybil",
    "Synesthesia",
    "Taboo",
    "TackleBox",
    "Taco Bull",
    "Tad Less",
    "Taffy Maker",
    "Tagline",
    "Tai Chi",
    "Taj Mahal",
    "Take-out",
    "Tally-Ho",
    "Tame Tiger",
    "Tank",
    "Tao",
    "Tap Dance",
    "Tar Pit",
    "Tasmania",
    "Tats",
    "Taxes R Theft",
    "Taylor Whiffed",
    "Technical Debt",
    "Teddy's Tavern",
    "Tee Off",
    "Teflon",
    "Tek War",
    "Telecaster",
    "Telefoam",
    "Temerity",
    "Tenacious",
    "Tequila",
    "Tercero",
    "Terminated",
    "Testing 1, 2, 3",
    "Third Martini",
    "Thirteenth Step",
    "Threadbare",
    "Three Somethings",
    "Thor's Hummer",
    "Tic Tac Toe",
    "Tickle Me",
    "Tied Up",
    "Tighter Pleese",
    "Tiller",
    "Tim bucked two",
    "Tin Horn",
    "Tip of the Iceberg",
    "Toggle",
    "Token Dude",
    "Toll Road",
    "Tomorrow",
    "Tone Deaf",
    "Too Tired",
    "Top Gear",
    "Top Hat",
    "Topless Tina's Tent",
    "Torrent",
    "Tostesterone",
    "Trader Cho",
    "Trans Sister",
    "Transylvania",
    "Treadstone",
    "Trellis",
    "Trouble",
    "Turtle Creek",
    "Turtle Eater",
    "Udder Failure",
    "Ugh",
    "Ukelele",
    "Ultimate Nothing",
    "Underwear",
    "Vanna Wyte",
    "Vending Machine",
    "Verve",
    "Vibraphone",
    "Vicky's Chow",
    "Villain",
    "vim",
    "Vanadium",
    "Welease Wodewick",
    "Xyzzy",
    "XL Academy",
    "Yag Laser",
    "Yard Store",
    "Yazoo City",
    "Yellow Bus Marine",
    "Yippee Kai Yay",
    "Yo Adrian",
    "Your mom is a port",
    "Zeus",
    "Zipline",
    "Zoom",
    "Zorro",
    "Zuplicate",
    "김밥",
    "天安门广场",
    "十面埋伏",
];
